config/routes.rb
Rails.application.routes.draw do
  resources :currency_conversions, shallow: true

  root to: 'currency_conversions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency_conversion.rb
class CurrencyConversion < ApplicationRecord

  AVAILABLE_CURRENCIES = %w(USD JPY COP EUR DKK GTQ CNY CLP XAF KYD CAD)

  validates_presence_of :from, :to, :actual_amount
  validate :distinctiveness_in_currency_types

  before_save :convert_amount

  enum to: AVAILABLE_CURRENCIES, _prefix: :to
  enum from: AVAILABLE_CURRENCIES, _prefix: :from

  def distinctiveness_in_currency_types
    if to == from
      errors.add(:base, I18n.t('errors.currency_conversions.distinguish_currency_types'))
    end
  end

  def convert_amount
    self.converted_amount = Concurrency.convert(actual_amount, from, to)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currency_conversions_controller.rb
class CurrencyConversionsController < ApplicationController
  before_action :set_currency_conversion, only: %i(new edit update)

  def create
    @currency_conversion = CurrencyConversion.new(permited_params)

    if @currency_conversion.save
      redirect_to edit_currency_conversion_path(@currency_conversion)
    else
      flash.now[:error] = @currency_conversion.errors.full_messages.flatten.to_sentence
      render :new
    end
  end

  def update
    unless @currency_conversion.update(permited_params)
      flash.now[:error] = @currency_conversion.errors.full_messages.flatten.to_sentence
    end

    render :edit
  end

  private

  def set_currency_conversion
    if params[:id].present?
      @currency_conversion = CurrencyConversion.find(params[:id])
    else
      @currency_conversion = CurrencyConversion.new
    end
  end

  def permited_params
    params.require(:currency_conversion).permit(:from, :to, :actual_amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  CRUD_ACTIONS = %w(create new edit update)

  CRUD_ACTIONS.each do |action_name|
    define_method "#{action_name}_action?" do
      params[:action] == action_name
    end
  end

  def flash_message_classes(type)
    case type.to_sym
    when :error
      'alert alert-danger'
    when :notice
      'alert alert-info'
    else
      ''
    end
  end

  def currency_dropdown(form, type)
    form.select type, options_for_select(
                        CurrencyConversion::AVAILABLE_CURRENCIES,
                        selected: @currency_conversion.send(type)
                      ),
                      { prompt: 'Select Currrency' },
                      { class: 'form-select', required: true }
  end
end

app/views/currency_conversions/_form.html.erb
<div class="border border-3 rounded-3 p-5 mt-5">

  <h1> Real Currency Conversion </h1>
  <%= form_for @currency_conversion do |f| %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

    <div class="input-group mt-5">
      <span class="input-group-text">From</span>
      <%= currency_dropdown(f, :from) %>
      <span class="input-group-text">Amount</span>
      <%= f.number_field :actual_amount, class: 'form-control', placeholder: '999.9', required: true %>
    </div>

    <div class="input-group mt-5">
      <span class="input-group-text"> To </span>
      <%= currency_dropdown(f, :to) %>
      <% if edit_action? || update_action? %>
        <span class="input-group-text">Converted Amount</span>
        <%= f.number_field :converted_amount, class: 'form-control text-light bg-success', id: 'disabledInput' %>
      <% end %>
    </div>

    <%= f.submit 'Convert', class: 'btn btn-primary mt-5' %>
  <% end %>
<div>

app/views/currency_conversions/edit.html.erb
<div class="container">
  <%= link_to 'New Currency Conversion', new_currency_conversion_path, class: 'btn btn-primary mt-3' %>
  <%= render 'form' %>
</div>

app/views/currency_conversions/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CurrencyConverter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="<%= flash_message_classes(type) %>">
    <%= msg %>
  </div>
<% end %>